### ISSUE TITLE
NullPointerException when opening the option menu via hardware button

### ISSUE THREAD

**Issue by hdmn** [wiglenet/wigle-wifi-wardriving#49]
Every time I try to open the option menu via hardware button, the app crashes. 
This device only, since current version (11/2014); others work fine. 
-hdmn

    WigleWifi error log - Feb 14, 2015 1:19:07 AM
    versionName: 2.6
    baseError: NullPointerException: null

    packageName: net.wigle.wigleandroid
    MODEL: LG-P710
    RELEASE: 4.1.2
    BOARD: 7x27
    BRAND: lge
    DEVICE: vee7e
    DISPLAY: JZO54K
    FINGERPRINT: lge/vee7e_open_eu/vee7e:4.1.2/JZO54K/P71010j-EUR-XX.1393575359:user/release-keys
    HOST: android-5pm-server-03
    ID: JZO54K
    PRODUCT: vee7e_open_eu
    TAGS: release-keys
    TIME: 1393575556000
    TYPE: user
    USER: rakwon.wi
    Thread: Thread[main,5,main] throwable: java.lang.NullPointerException

    java.lang.NullPointerException
    at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:1004)
    at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1712)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2125)
    at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3611)
    at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3581)
    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2831)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4929)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by hdmn** [comment]
sorry, never mind. 
seems to have been a problem with the lg software. 'astro file manager' was showing the same behavior. android update to 4.4.2 fixed the problem. (after a reeeally long night with emergency mode and reflashing the firmware…) 
anyway, thanks for your great work! 
-hdmn
